server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
  datasource:
    username: sinology
    password: sinology@ljx.com2019&10$20
    url: jdbc:mysql://39.106.25.67:13320/db2020?useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #    initialSize: 5
  #    minIdle: 5
  #    maxActive: 20
  #    maxWait: 60000
  #    timeBetweenEvictionRunsMillis: 60000
  #    minEvictableIdleTimeMillis: 300000
  #    validationQuery: SELECT 1 FROM DUAL
  #    testWhileIdle: true
  #    testOnBorrow: false
  #    testOnReturn: false
  #    poolPreparedStatements: true
  #    filters: config,stat,wall,slf4j
  #    maxPoolPreparedStatementPerConnectionSize: 20
  #    useGlobalDataSourceStat: true
  #    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.spring.bean

eureka:
  client:
    #true向Eureka server服务中心注册自己
    register-with-eureka: true
    #是否从Eureka server 抓起已有的注册信息,默认为true.单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #,http://eureka7002.org:7002/eureka
      defaultZone: http://eureka7001.org:7001/eureka
  instance:
    instance-id: payment8001
    #访问路径可以显示IP地址
    prefer-ip-address: true